---
- name: Déployer Apache via Docker
  hosts: prod
  become: yes
  vars_files:
       - vars.yml
  pre_tasks:
    - name: Install EPEL repo
      package: name=epel-release state=present
      when: ansible_distribution == "CentOS"
      
    - name: Download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
        
    - name: Install python-pip
      ansible.builtin.command: python2.7 /tmp/get-pip.py
      
    - name: Install docker python
      pip: name=docker-py
      
  tasks:

    - name: Installer les paquets requis (git et wget) uniquement sur CentOS
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - wget
      when: ansible_facts['os_family'] == "RedHat"

    - name: Créer un répertoire pour stocker l'index.html
      file:
        path: "{{ website_dir }}"
        state: directory
        mode: '0755'

    - name: Générer la page d'accueil index.html
      template:
        src: "{{ template_src }}"
        dest: "{{ template_dest }}"
        
    - name: Vérifier si Docker est installé
      command: docker --version
      changed_when: false

    - name: Créer et démarrer un conteneur Apache
      docker_container:
        name: webapp
        image: httpd:latest
        state: started
        restart_policy: always
        ports:
          - "{{ apache_port }}"
        volumes:
          - "{{ apache_volumes }}"

    - name: Vérifier que le conteneur Apache fonctionne
      command: docker ps -f "name=webapp"
      register: apache_running
      changed_when: false

    - name: Afficher l'état du conteneur
      debug:
        msg: "{{ apache_running.stdout_lines }}"
